name: Build & Test & Clippy

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cancel_previous_runs:
    name: Cancel Previous Runs
    runs-on: ubuntu-20.04
    steps:
      - uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Rust check ${{ matrix.check }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        # We need to compile `test-no-std` separately, otherwise we have std leaks from the build-deps.
        #
        # `test-no-std` is only meant to check if the `substrate-api-client` compiles to `no_std`, hence
        # we omit clippy and test there.
        check: [ cargo build --release --all
                 cargo clippy --all
                 cargo clippy --examples -- -D warnings,
                 cargo test --all --exclude
                 cargo fmt --all -- --check,
        ]
    steps:
      - uses: actions/checkout@v2
      - name: init-rust-target
        run: rustup show

      - uses: Swatinem/rust-cache@v1
        with:
          key: ${{ matrix.check }}

      - name: ${{ matrix.check }}
        run: ${{ matrix.check }}
